//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PipingRockERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alergen
    {
        public int AlergenID { get; set; }
        public string Alergen1 { get; set; }
        public System.DateTime AlergenAddedDate { get; set; }
        public System.DateTime AlergenChangedDate { get; set; }
        public Nullable<System.DateTime> AlergenDeletedDate { get; set; }
        public int AlergenModifiedById { get; set; }
    }
}
