//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PipingRockERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bottle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bottle()
        {
            this.FinishedGoods = new HashSet<FinishedGood>();
        }
    
        public int BottleId { get; set; }
        public string BottleItemKey { get; set; }
        public string BottleDescription { get; set; }
        public int BottlesSmallTray { get; set; }
        public int BottlesLargeTray { get; set; }
        public int WrappedBottlesTrayLarge { get; set; }
        public int WrappedBottlesTraySmall { get; set; }
        public int ItemStatusId { get; set; }
        public int ItemTypeId { get; set; }
        public int ItemTypeDetailId { get; set; }
        public decimal BottleLength { get; set; }
        public decimal BottleWidth { get; set; }
        public decimal BottleHieght { get; set; }
        public decimal BottleCubicInches { get; set; }
        public decimal BottleLengthWrapped { get; set; }
        public decimal BottleWidthWrapped { get; set; }
        public decimal BottleDepthWrapped { get; set; }
        public decimal BottleCubicInchWrapped { get; set; }
        public decimal BottleLabelSquareInches { get; set; }
        public System.DateTime BottleAddedDate { get; set; }
        public System.DateTime BottleChangedDate { get; set; }
        public Nullable<System.DateTime> BottleDeletedDate { get; set; }
        public int BottleModifiedById { get; set; }
        public bool isDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinishedGood> FinishedGoods { get; set; }
    }
}
