//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PipingRockERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemTypeDetail
    {
        public int ItemTypeDetailId { get; set; }
        public int ItemTypeId { get; set; }
        public string ItemTypeDetail1 { get; set; }
        public string ItemTypeDetailDescription { get; set; }
        public decimal LossFactorInventory { get; set; }
        public decimal LossFactorCost { get; set; }
        public System.DateTime ItemTypeDetailAddedDate { get; set; }
        public System.DateTime ItemTypeDetailChangedDate { get; set; }
        public Nullable<System.DateTime> ItemTypeDetailDeletedDate { get; set; }
        public int ItemTypeDetailModifiedById { get; set; }
    
        public virtual ItemType ItemType { get; set; }
    }
}
