//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PipingRockERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuarantineType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuarantineType()
        {
            this.Bulks = new HashSet<Bulk>();
        }
    
        public int QuarantineTypeId { get; set; }
        public string QuarantineType1 { get; set; }
        public System.DateTime QuarantineTypeAddedDate { get; set; }
        public System.DateTime QuarantineTypeChangedDate { get; set; }
        public Nullable<System.DateTime> QuarantineTypeDeletedDate { get; set; }
        public int QuarantineTypeModifiedById { get; set; }
        public bool isDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bulk> Bulks { get; set; }
    }
}
